/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseHeader: typeof import('./components/layouts/BaseHeader.vue')['default']
    BaseSide: typeof import('./components/layouts/BaseSide.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    GuitarTab: typeof import('./components/GuitarTab.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Logos: typeof import('./components/Logos.vue')['default']
    MessageBoxDemo: typeof import('./components/MessageBoxDemo.vue')['default']
    MidiPlayer: typeof import('./components/MidiPlayer.vue')['default']
    MidiRecorder: typeof import('./components/MidiRecorder.vue')['default']
    NumberedNotation: typeof import('./components/NumberedNotation.vue')['default']
    PianoRollVisualizer: typeof import('./components/PianoRollVisualizer.vue')['default']
    PianoRollWebGPU: typeof import('./components/PianoRollWebGPU.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScoreViewer: typeof import('./components/ScoreViewer.vue')['default']
    StaffEditor: typeof import('./components/StaffEditor.vue')['default']
    StaffNotation: typeof import('./components/StaffNotation.vue')['default']
    UploadMIDI: typeof import('./components/UploadMIDI.vue')['default']
  }
}
